version: '3.8'

services:
  db:
    image: postgres:13
    container_name: real_estate_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: .
    container_name: real_estate_scraper
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/real_estate
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: