name: Run Real Estate Scraper
on:
  schedule:
    - cron: '0 14 * * *' # Run every day at 14:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
      - name: Run scraper
        env:
          TELEGRAM_BOT_TOKEN: {{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: {{secrets.TELEGRAM_CHAT_ID}}
        run: python main.py